Loading the libraries

In [1]:
import sys
import os
import pandas as pd

# Add scripts directory to path
project_root = os.path.abspath('..')  # Go up to project root
scripts_path = os.path.join(project_root, 'scripts')
sys.path.insert(0, scripts_path)

# Now import
from utils import load_data  # Not "from scripts.utils"

# Load data
df = load_data()

FileNotFoundError: No cleaned data found. Please run clean.py first.
Expected: /Users/gracewang/Documents/Hertie/Data Structures & Algorithms/project-chaggg/data/cleaned/chicago_crimes_cleaned.csv or /Users/gracewang/Documents/Hertie/Data Structures & Algorithms/project-chaggg/data/cleaned/chicago_crimes_cleaned.parquet

In [2]:
df.head()

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,updated_on,x_coordinate,y_coordinate,latitude,longitude,time,month,day,day_of_week,hour
0,1969564,HH162926,2002-01-01,063XX N WASHTENAW AV,0820,THEFT,$500 AND UNDER,STREET,False,False,...,2018-02-28T15:56:25.000,1157181.0,1941908.0,41.996366,-87.697157,00:00:00,1,1,1,0
1,1921971,HH105505,2002-01-01,085XX S CRANDON AV,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,...,2018-02-28T15:56:25.000,1192988.0,1848862.0,41.740240,-87.568491,00:00:00,1,1,1,0
2,1989110,HH188541,2002-01-01,047XX N HERMITAGE AV,0820,THEFT,$500 AND UNDER,RESIDENCE,False,False,...,2018-02-28T15:56:25.000,1163946.0,1931450.0,41.967528,-87.672569,00:00:00,1,1,1,0
3,1917950,HH101092,2002-01-01,028XX N PARKSIDE AV,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,2018-02-28T15:56:25.000,1138221.0,1918236.0,41.931773,-87.767479,00:00:00,1,1,1,0
4,1950239,HH139701,2002-01-01,066XX S KEDVALE AV,0842,THEFT,AGG: FINANCIAL ID THEFT,RESIDENCE,False,False,...,2018-02-28T15:56:25.000,1149846.0,1860270.0,41.772489,-87.726264,00:00:00,1,1,1,0

In [4]:
df = pd.read_parquet('/Users/yuriirrgang/Library/Mobile Documents/com~apple~CloudDocs/Hertie/project-chaggg/data/cleaned/chicago_crimes_cleaned.parquet')
df.head()

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,year,updated_on,x_coordinate,y_coordinate,latitude,longitude,time
0,13246664,JG467702,2001-01-01,045XX N CENTRAL PARK AVE,0281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,False,...,33.0,14.0,02,2001,2023-10-21T15:42:03.000,NaN,NaN,NaN,NaN,00:00:00
1,13714017,JH548973,2001-01-01,051XX W MEDILL AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,...,31.0,19.0,17,2001,2025-01-11T15:40:58.000,NaN,NaN,NaN,NaN,00:00:00
2,13714063,JH548896,2001-01-01,051XX W MEDILL AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,...,31.0,19.0,17,2001,2025-01-11T15:40:58.000,NaN,NaN,NaN,NaN,00:00:00
3,1310933,G001704,2001-01-01,0000X W WACKER DR,0810,THEFT,OVER $500,PARKING LOT/GARAGE(NON.RESID.),False,False,...,NaN,NaN,06,2001,2015-08-17T15:03:40.000,1176294.0,1902094.0,41.886704,-87.628054,00:00:00
4,1432149,G156662,2001-01-01,002XX E DELAWARE PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,...,NaN,NaN,26,2001,2015-08-17T15:03:40.000,1178492.0,1906652.0,41.899161,-87.619844,00:00:00